import 'package:flutter/material.dart';

const borderRadius4 = BorderRadius.all(Radius.circular(4));
const borderRadius5 = BorderRadius.all(Radius.circular(5));
const borderRadius8 = BorderRadius.all(Radius.circular(8));
const borderRadius10 = BorderRadius.all(Radius.circular(10));
const borderRadius12 = BorderRadius.all(Radius.circular(12));
const borderRadius15 = BorderRadius.all(Radius.circular(15));
const borderRadius16 = BorderRadius.all(Radius.circular(16));
const borderRadius20 = BorderRadius.all(Radius.circular(20));
const borderRadius25 = BorderRadius.all(Radius.circular(25));
const borderRadius30 = BorderRadius.all(Radius.circular(30));
const borderRadius35 = BorderRadius.all(Radius.circular(35));
const borderRadius40 = BorderRadius.all(Radius.circular(40));
const borderRadius50 = BorderRadius.all(Radius.circular(50));
const borderRadius60 = BorderRadius.all(Radius.circular(60));
const borderRadius70 = BorderRadius.all(Radius.circular(70));
const borderRadius80 = BorderRadius.all(Radius.circular(80));
const borderRadius90 = BorderRadius.all(Radius.circular(90));
const borderRadius100 = BorderRadius.all(Radius.circular(100));
