include: package:flutter_lints/flutter.yaml

dart_code_metrics:
  extends:
    - recommended

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
