name: myplaces_mexico
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  bloc_test: 10.0.0
  device_preview: 1.2.0
  dio: 5.8.0+1
  firebase_core: 3.13.1
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  flutter_svg: 2.1.0
  freezed_annotation: 2.4.4
  geolocator: 14.0.1
  go_router: 15.1.2
  google_fonts: 6.2.1
  google_maps_flutter: 2.12.2
  json_annotation: 4.9.0
  logging: 1.3.0
  mocktail: 1.0.4
  pretty_dio_logger: 1.4.0
  rive: 0.13.20
  url_launcher: 6.3.1

dev_dependencies:
  build_runner: 2.4.15
  flutter_gen_runner: 5.10.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: 6.9.5
  very_good_analysis: ^9.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/pages/home_page/
    - assets/images/
    - assets/animations/
