name: myplaces_mexico
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  device_preview: ^1.1.0
  dio: ^5.3.2
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  geolocator: ^10.1.0
  go_router: ^12.1.3
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.5.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2
flutter:
  uses-material-design: true
  assets:
    - assets/pages/home_page/
    - assets/images/
