name: myplaces_mexico
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  device_preview: ^1.1.0
  dio: ^5.4.2+1
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  pretty_dio_logger: ^1.3.1
  rive: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/pages/home_page/
    - assets/images/
    - assets/animations/
