name: myplaces_mexico
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none' 

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  pretty_dio_logger: ^1.2.0-beta-1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
flutter:
  uses-material-design: true
