name: myplaces_mexico
description: A new Flutter project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  bloc_test: ^10.0.0
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  firebase_core: ^3.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  geolocator: ^13.0.2
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  mocktail: ^1.0.4
  pretty_dio_logger: ^1.4.0
  rive: ^0.13.20
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^3.0.0-0.0.dev
  json_serializable: ^6.9.3
  flutter_gen_runner: ^5.8.0
flutter:
  uses-material-design: true
  assets:
    - assets/pages/home_page/
    - assets/images/
    - assets/animations/
